kind: pipeline
type: docker
name: build dev

steps:
- name: build and push image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    registry: registry.solidstage.de
    repo: registry.solidstage.de/library/randomboi
    username:
      from_secret: harbor_username
    password:
      from_secret: harbor_password
    tags:
      - dev
      - "${DRONE_COMMIT:0:8}"

trigger:
  branch:
    - dev

---

kind: pipeline
type: docker
name: build master

steps:
- name: build and push image
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    registry: registry.solidstage.de
    repo: registry.solidstage.de/library/randomboi
    username:
      from_secret: harbor_username
    password:
      from_secret: harbor_password
    tags:
      - latest
      - "${DRONE_COMMIT:0:8}"

trigger:
  branch:
    - master
